from enum import Enum

# POST MEDIA
POST_MEDIA_ID_LENGTH: int = 36
MEDIA_URL_LENGTH: int = 255

# PROFILE ACCESSORIES
ACCESSORY_ID_LENGTH: int = 36
ACCESSORY_NAME_LENGTH_MIN: int = 3
ACCESSORY_NAME_LENGTH_MAX: int = 50

# JWT TOKEN BLOCKLIST
JWT_TOKEN_BLOCKLIST_ID_LENGTH: int = 36
JTI_LENGTH: int = 36

# USERS
USER_PRIVATE_ID_LENGTH: int = 7

# USER GROUPS
USER_GROUP_PRIVATE_ID_LENGTH: int = 36

# HASHTAGS
HASHTAG_ID_LENGTH: int = 36
HASHTAG_NAME_LENGTH_MIN: int = 1
HASHTAG_NAME_LENGTH_MAX: int = 20

# POSTS
POST_ID_LENGTH: int = 36

# POST REACTION TYPES
POST_REACTION_TYPE_LENGTH: int = 20

# POST CATEGORIES
POST_CATEGORY_ID_LENGTH: int = 36
POST_CATEGORY_NAME_LENGTH_MAX: int = 50
POST_CATEGORY_NAME_LENGTH_MIN: int = 3

# POST COMMENTS
POST_COMMENT_ID_LENGTH: int = 36
PARENT_POST_COMMENT_ID_LENGTH: int = POST_COMMENT_ID_LENGTH

# POST COMMENT LIKES
POST_COMMENT_LIKE_ID_LENGTH: int = 36