from enum import Enum

# PAGANATION
PAGE: int = 1
PER_PAGE: int = 20
PER_PAGE_LIMIT: int = 100
PAGE_LIMIT: int = 10 ** 6

# POST MEDIA
POST_MEDIA_ID_LENGTH: int = 36
MEDIA_URL_LENGTH: int = 255

# PROFILE ACCESSORIES
ACCESSORY_ID_LENGTH: int = 36
ACCESSORY_NAME_LENGTH_MIN: int = 3
ACCESSORY_NAME_LENGTH_MAX: int = 50

# JWT TOKEN BLOCKLIST
JWT_TOKEN_BLOCKLIST_ID_LENGTH: int = 36
JTI_LENGTH: int = 36

# USERS
USER_PRIVATE_ID_LENGTH: int = 36
USER_PUBLIC_ID_LENGTH: int = 7
USER_BIOGRAPHY_TEXT_LIMIT: int = 500
USER_USERNAME_LENGTH_MIN: int = 5
USER_USERNAME_LENGTH_MAX: int = 20
USER_EMAIL_LENGTH: int = 255
USER_FRIEND_CODE_LENGTH: int = 7
USER_PASSWORD_HASH_LENGTH: int = 255
USER_PROFILE_PICTURE_URL_LENGTH: int = 255
USER_GENDER_LENGTH: int = 20
USER_COUNTRY_LENGTH: int = 255
USER_ORIENTATION_LENGTH: int = 20

# USER_FOLLOWERS
FOLLOWER_ID_LENGTH: int = 36

# OWNED ACCESSORIES
OWNED_ACCESSORY_ID_LENGTH: int = 36

# BLOCKED USERS
BLOCKED_USERS_ID_LENGTH: int = 36


# USER GROUPS
USER_GROUP_PRIVATE_ID_LENGTH: int = 36

# HASHTAGS
HASHTAG_ID_LENGTH: int = 36
HASHTAG_NAME_LENGTH_MIN: int = 1
HASHTAG_NAME_LENGTH_MAX: int = 20

# POSTS
POST_ID_LENGTH: int = 36

# POST REACTION TYPES
POST_REACTION_TYPE_LENGTH: int = 20

# POST CATEGORIES
POST_CATEGORY_ID_LENGTH: int = 36
POST_CATEGORY_NAME_LENGTH_MAX: int = 50
POST_CATEGORY_NAME_LENGTH_MIN: int = 3

# POST COMMENTS
POST_COMMENT_ID_LENGTH: int = 36
PARENT_POST_COMMENT_ID_LENGTH: int = POST_COMMENT_ID_LENGTH

# POST COMMENT LIKES
POST_COMMENT_LIKE_ID_LENGTH: int = 36